/**
 * Mock transport. Serves the §11 fixtures with a small simulated latency so
 * the UI can be developed without a running backend (`VITE_API_MODE=mock`).
 * The fixture files carry the exact keys the service emits (§11 / MAP_CONTRACT).
 */

import { ApiError, type Transport } from "../transport";
import type {
  AlgorithmSummary,
  AlgorithmsResponse,
  GraphResponse,
  HealthResponse,
  HistoryResponse,
  SearchResponse,
  VersionResponse,
} from "../types";
import graphFixture from "../fixtures/graph.json";
import searchBfsFixture from "../fixtures/search.json";
import searchDfsFixture from "../fixtures/search-dfs.json";
import searchUcsFixture from "../fixtures/search-ucs.json";
import searchGreedyFixture from "../fixtures/search-greedy.json";
import searchAstarFixture from "../fixtures/search-astar.json";

const LATENCY_MS = 120;

/** Mirrors the service `AlgorithmCatalog` (ui/service/backends.py) exactly. */
const CATALOG: AlgorithmSummary[] = [
  { id: "bfs", label: "Breadth-First Search", mock: false },
  { id: "dfs", label: "Depth-First Search", mock: true },
  { id: "ucs", label: "Uniform-Cost Search", mock: true },
  { id: "greedy", label: "Greedy Best-First Search", mock: true },
  { id: "astar", label: "A* Search", mock: true },
];

/** Per-algorithm fixtures generated by the real service mocks (§6.6). */
const SEARCH_FIXTURES: Record<string, unknown> = {
  bfs: searchBfsFixture,
  dfs: searchDfsFixture,
  ucs: searchUcsFixture,
  greedy: searchGreedyFixture,
  astar: searchAstarFixture,
};

function delay(): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, LATENCY_MS));
}

function asGraphResponse(data: unknown): GraphResponse {
  return data as GraphResponse;
}

export class MockClient implements Transport {
  async getGraph(): Promise<GraphResponse> {
    await delay();
    return asGraphResponse(graphFixture);
  }

  async getHealth(): Promise<HealthResponse> {
    await delay();
    return { status: "ok" };
  }

  async search(
    algorithm: string,
    _start: string,
    _goal: string,
    _enableLogging?: boolean,
  ): Promise<SearchResponse> {
    await delay();
    return (SEARCH_FIXTURES[algorithm] ?? searchBfsFixture) as SearchResponse;
  }

  async listAlgorithms(): Promise<AlgorithmsResponse> {
    await delay();
    return { algorithms: [...CATALOG] };
  }

  async getHistory(): Promise<HistoryResponse> {
    await delay();
    return { runs: [] };
  }

  async getVersion(): Promise<VersionResponse> {
    await delay();
    return {
      service: "hcmc-ai-ui-service",
      version: "1.0.0",
      api_version: "1.0",
    };
  }

  /** Throws a §7-shaped error; used by tests to simulate failure paths. */
  static reject(code: string, message: string): never {
    throw new ApiError(code, message);
  }
}